// Generated by CoffeeScript 1.6.3
(function() {
  document.addEventListener('DOMContentLoaded', function(event) {
    var shadowDropdown;
    return shadowDropdown = new CustomDropdown();
  });

}).call(this);
