// Generated by CoffeeScript 1.6.3
(function() {
  document.addEventListener('DOMContentLoaded', function(event) {
    var customDropdown;
    return customDropdown = new CustomDropdown();
  });

}).call(this);
