// Generated by CoffeeScript 1.6.3
(function() {
  document.addEventListener('DOMContentLoaded', function(event) {
    var customDropdown, shadowTemplate;
    customDropdown = new CustomDropdown();
    return shadowTemplate = new ShadowTemplate('template', '.link-list');
  });

}).call(this);
